// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SampleForge.Infrastructure;

#nullable disable

namespace SampleForge.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251031204337_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SampleForge.Domain.Entities.Pack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("text")
                        .HasColumnName("coverImagePath");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("packs", (string)null);
                });

            modelBuilder.Entity("SampleForge.Domain.Entities.PackSample", b =>
                {
                    b.Property<Guid>("PackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid");

                    b.HasKey("PackId", "SampleId");

                    b.HasIndex("SampleId");

                    b.ToTable("pack_samples", (string)null);
                });

            modelBuilder.Entity("SampleForge.Domain.Entities.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Bpm")
                        .HasColumnType("integer")
                        .HasColumnName("bpm");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filePath");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("samples", (string)null);
                });

            modelBuilder.Entity("SampleForge.Domain.Entities.SampleTag", b =>
                {
                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("SampleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("sample_tags", (string)null);
                });

            modelBuilder.Entity("SampleForge.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("SampleForge.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SampleForge.Domain.Entities.Pack", b =>
                {
                    b.HasOne("SampleForge.Domain.Entities.User", "User")
                        .WithMany("Packs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SampleForge.Domain.Entities.PackSample", b =>
                {
                    b.HasOne("SampleForge.Domain.Entities.Pack", "Pack")
                        .WithMany("Samples")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SampleForge.Domain.Entities.Sample", "Sample")
                        .WithMany("Packs")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pack");

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("SampleForge.Domain.Entities.Sample", b =>
                {
                    b.HasOne("SampleForge.Domain.Entities.User", "User")
                        .WithMany("Samples")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SampleForge.Domain.Entities.SampleTag", b =>
                {
                    b.HasOne("SampleForge.Domain.Entities.Tag", "Tag")
                        .WithMany("Samples")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SampleForge.Domain.Entities.Sample", "Sample")
                        .WithMany("Tags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sample");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SampleForge.Domain.Entities.Pack", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("SampleForge.Domain.Entities.Sample", b =>
                {
                    b.Navigation("Packs");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("SampleForge.Domain.Entities.Tag", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("SampleForge.Domain.Entities.User", b =>
                {
                    b.Navigation("Packs");

                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
